databases:
  - name: PokeRails
    databaseName: PokeRails
    user: PokeRails

services:
  - type: web
    name: PokeRails
    runtime: ruby
    buildCommand: "./bin/render-build.sh"
    startCommand: "bundle exec puma -C config/puma.rb"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: PokeRails
          property: connectionString
      - key: RAILS_MASTER_KEY
        sync: false
